# Generated by Django 4.2 on 2023-04-17 18:07

from django.db import migrations, models
import zeon.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=255, unique=True, verbose_name='Процессор')),
                ('gpu', models.CharField(max_length=255, null=True, unique=True, verbose_name='Видеокарта')),
                ('operativka', models.CharField(max_length=255, null=True, unique=True, verbose_name='Оперативная память')),
                ('mother', models.CharField(max_length=255, null=True, unique=True, verbose_name='Материнская плата')),
                ('ssd', models.CharField(max_length=255, null=True, unique=True, verbose_name='ССД')),
                ('hdd', models.CharField(max_length=255, null=True, unique=True, verbose_name='Жесткий диск')),
                ('corpus', models.CharField(max_length=255, null=True, unique=True, verbose_name='Корпус')),
                ('perifiria', models.CharField(max_length=255, null=True, unique=True, verbose_name='Периферия')),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to=zeon.models.upload_to_images, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
        migrations.CreateModel(
            name='Tarifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('opisanie', models.CharField(max_length=255, null=True, unique=True, verbose_name='Описание')),
                ('price', models.CharField(max_length=255, null=True, unique=True, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, db_index=True, null=True, upload_to=zeon.models.upload_to_images, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
            },
        ),
    ]
